name: Security Scanning Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    # Build your project, skip tests to speed up (required for Sonar scan)
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # SonarQube / SonarCloud SAST scan
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.organization=your-organization-key \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=$SONAR_TOKEN

    # OWASP Dependency Check - SCA scan
    - name: Dependency Check Scan
      uses: dependency-check/dependency-check-action@v2
      with:
        scan-path: './'
        format: 'ALL'
        fail-on-vulnerabilities: true
