name: Security Scanning Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # For PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Dependency Check Scan
        run: mvn org.owasp:dependency-check-maven:check
